"""Tests for the gradebook. Run from this folder:

    python3 -m unittest -v

Do not edit this file. The code under test is gradebook.py and report.py.
"""
import unittest
from gradebook import Student, load_students, average, letter, rank, top
from report import format_row, report

DATA = "data/students.csv"


class LoadTests(unittest.TestCase):
    def test_five_students(self):
        self.assertEqual(len(load_students(DATA)), 5)

    def test_names_are_clean(self):
        names = [s.name for s in load_students(DATA)]
        self.assertEqual(names, ["Ada", "Grace", "Linus", "Margaret", "Tim"])

    def test_scores_parsed(self):
        ada = load_students(DATA)[0]
        self.assertEqual(ada.scores, [90, 85, 77])

    def test_missing_scores(self):
        tim = load_students(DATA)[4]
        self.assertEqual(tim.scores, [])


class AverageTests(unittest.TestCase):
    def test_average_is_exact(self):
        self.assertEqual(average([90, 85, 77]), 84.0)
        self.assertEqual(average([92, 88, 90]), 90.0)
        self.assertEqual(average([88, 90, 92, 91]), 90.25)

    def test_average_of_nothing(self):
        self.assertEqual(average([]), 0.0)


class LetterTests(unittest.TestCase):
    def test_boundaries(self):
        self.assertEqual(letter(90), "A")
        self.assertEqual(letter(89.9), "B")
        self.assertEqual(letter(80), "B")
        self.assertEqual(letter(70), "C")
        self.assertEqual(letter(60), "D")
        self.assertEqual(letter(59.9), "F")

    def test_top_end(self):
        self.assertEqual(letter(100), "A")


class RankTests(unittest.TestCase):
    def test_highest_first(self):
        ranked = rank(load_students(DATA))
        self.assertEqual(ranked[0].name, "Grace")

    def test_ties_by_name(self):
        tied = [Student("Zoe", [80]), Student("Amir", [80]), Student("Kai", [80])]
        self.assertEqual([s.name for s in rank(tied)], ["Amir", "Kai", "Zoe"])

    def test_top_two(self):
        names = [s.name for s in top(load_students(DATA), 2)]
        self.assertEqual(names, ["Grace", "Margaret"])


class ReportTests(unittest.TestCase):
    def test_row_format(self):
        self.assertEqual(format_row(1, Student("Ada", [90, 85, 77])), "1. Ada       84.0  B")

    def test_full_report(self):
        expected = "\n".join([
            "1. Grace     90.0  A",
            "2. Margaret  90.0  A",
            "3. Ada       84.0  B",
            "4. Linus     70.0  C",
            "5. Tim       0.0  F",
        ])
        self.assertEqual(report(load_students(DATA)), expected)

    def test_top_three_report(self):
        lines = report(load_students(DATA), 3).splitlines()
        self.assertEqual(len(lines), 3)
        self.assertTrue(lines[2].startswith("3. Ada"))


if __name__ == "__main__":
    unittest.main()
